gitops:
  manifest_projects:
  - id: mycpu-prg-knightrider
    ref: # either `branch`, `tag` or `commit` can be specified
      branch: production
      # commit: <mysha>
      # tag: v1.0
    default_namespace: gitlab-mycpu
    paths:
      # Read all YAML files from this directory.
    - glob: '/*.yaml'
    reconcile_timeout: 3600s
    dry_run_strategy: none
    prune: true
    prune_timeout: 3600s
    prune_propagation_policy: foreground
    inventory_policy: must_match
